### ISSUE TITLE
添加404页面

### ISSUE THREAD

**Issue by qzcf** [sqrt-7-qhfz/sqrt-7-qhfz.github.io#1]
优化你的网站，添加404界面

**Comment by sqrt-7-qhfz** [comment]
然而我现在遇到了一个问题，就是上传到GitHub上的代码能看到，但是访问网站时就没有。。。

**Comment by sqrt-7-qhfz** [comment]
CQY，我刚看到你的代码，但是我并没有合并分支（需要我合并分支你提交的才算），因为我之前弄了一个404。你可以看看。
